# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roster.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Roster(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1189, 882)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1151, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 1151, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStandings = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnStandings.setObjectName("btnStandings")
        self.horizontalLayout.addWidget(self.btnStandings)
        self.btnScores = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnScores.setObjectName("btnScores")
        self.horizontalLayout.addWidget(self.btnScores)
        self.btnSchedule = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSchedule.setObjectName("btnSchedule")
        self.horizontalLayout.addWidget(self.btnSchedule)
        self.btnStats = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnStats.setObjectName("btnStats")
        self.horizontalLayout.addWidget(self.btnStats)
        self.btnTeams = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnTeams.setObjectName("btnTeams")
        self.horizontalLayout.addWidget(self.btnTeams)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(300, 250, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(600, 250, 47, 13))
        self.label_3.setObjectName("label_3")
        self.cmbx_MLBTeams = QtWidgets.QComboBox(Form)
        self.cmbx_MLBTeams.setGeometry(QtCore.QRect(338, 251, 211, 21))
        self.cmbx_MLBTeams.setObjectName("cmbx_MLBTeams")
        self.cmbx_Season = QtWidgets.QComboBox(Form)
        self.cmbx_Season.setGeometry(QtCore.QRect(660, 250, 75, 22))
        self.cmbx_Season.setObjectName("cmbx_Season")
        self.tblWg_Roster = QtWidgets.QTableWidget(Form)
        self.tblWg_Roster.setGeometry(QtCore.QRect(320, 300, 400, 511))
        self.tblWg_Roster.setObjectName("tblWg_Roster")
        self.tblWg_Roster.setColumnCount(3)
        self.tblWg_Roster.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblWg_Roster.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWg_Roster.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWg_Roster.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Teams"))
        self.btnStandings.setText(_translate("Form", "Standings"))
        self.btnScores.setText(_translate("Form", "Scores"))
        self.btnSchedule.setText(_translate("Form", "Schedule"))
        self.btnStats.setText(_translate("Form", "Stats"))
        self.btnTeams.setText(_translate("Form", "Teams"))
        self.label_2.setText(_translate("Form", "Team"))
        self.label_3.setText(_translate("Form", "Season"))
        item = self.tblWg_Roster.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Number (#)"))
        item = self.tblWg_Roster.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Position"))
        item = self.tblWg_Roster.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Player Name"))
